name: Kill and Launch Fargate Tasks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kill_and_launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: List Fargate tasks
        id: list_tasks
        run: |
          tasks=$(aws ecs list-tasks --cluster ${{ secrets.CLUSTER_NAME }} --query 'taskArns' --output text)
          echo "::set-output name=tasks::$tasks"

      - name: Stop Fargate tasks
        if: steps.list_tasks.outputs.tasks != ''
        run: |
          for task in ${{ steps.list_tasks.outputs.tasks }}; do
            aws ecs stop-task --cluster ${{ secrets.CLUSTER_NAME }} --task $task
          done

      - name: Launch new Fargate task
        run: |
          aws ecs run-task --cluster ${{ secrets.CLUSTER_NAME }} --task-definition ${{ secrets.TASK_DEFINITION_ARN }} --launch-type FARGATE --network-configuration 'awsvpcConfiguration={subnets=[subnet-0ef2bc1ee2d724800, subnet-021d055dfbea1d814, subnet-031158147fe1e8735],securityGroups=[sg-06e1a44394942e4d0],assignPublicIp=ENABLED'}
