name: Java CI with Maven Wrapper and Test Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'

    - name: Grant execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build with Maven Wrapper
      run: ./mvnw -B package --file pom.xml

    - name: Test with Maven Wrapper
      run: ./mvnw -B test --file pom.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()  # Ensures that test results are uploaded even if the test step fails
      with:
        name: junit-reports
        path: '**/target/surefire-reports/*.xml'

    - name: Publish Unit Test Results
      uses: actions/upload-test-results@v1
      if: always()  # Ensures that test results are published even if the test step fails
      with:
        files: '**/target/surefire-reports/*.xml'
